name: Send Update to Private Server Repos

on:
  push:
    branches:
      - main

jobs:
  update-private-repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: 
          - Bestrust-Servers/Bestrust-Vanilla-Server-Files
          - Bestrust-Servers/Bestrust-Modded-Server-Files
      fail-fast: false 

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.target_repo }}
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          submodules: true

      - name: Update the Submodule Pointer
        run: |
          git submodule update --remote oxide/lang

      - name: Commit and Push to Target Repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add oxide/lang
          
          # This line prevents the Action from crashing if the pointer didn't actually change
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-updated language submodule pointer" && git push origin main)
